project:
  type: website

website:
  title: "Digital Scholarship Graduate Fellows"
  page-footer: 
    left: <a href="https://digitalscholarship.brynmawr.edu">Digital Scholarship @ Bryn Mawr College</a>
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.md
      - icon: github
        href: https://github.com/digbmc/dsgf
  sidebar:
    style: docked
    contents:
    # contents: auto
    - text: "Syllabus"
      href: syllabus.md
    - auto: meetings
    - auto: resources
    - text: Logs
      href: logs.md
    - expectations.md


format:
  html:
    theme: cyborg
    css: styles.css
    toc: true


