project:
  type: website

website:
  title: "Digital Scholarship Graduate Fellows"
  page-footer: 
    left: <a href="https://digitalscholarship.brynmawr.edu">Digital Scholarship @ Bryn Mawr College</a>
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.md
      - icon: github
        href: https://github.com/digbmc/dsgf
  sidebar:
    style: docked
    contents: auto
      # - text: "Syllabus"
      #   href: syllabus.md
      # - section: "Meeting notes"
      #   contents: meetings
      # - section: "Resources"
      #   contents: resources
      # - section: "Workshops"
      #   contents: workshops

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true


